language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - BUILD_TYPE=Release

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - BUILD_TYPE=Debug

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Release

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && LINK_FLAGS=-fuse-ld=gold"
        - BUILD_TYPE=Debug

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - lcov
      env:
        - MATRIX_EVAL="COVERAGE=1 && CC=gcc-8 && CXX=g++-8 && CXX_FLAGS=--coverage && LINK_FLAGS=-fuse-ld=gold"
        - BUILD_TYPE=Debug

    - os: osx
      compiler: clang
      osx_image: xcode10
      env:
        - BUILD_TYPE=Release

    - os: osx
      compiler: clang
      osx_image: xcode10
      env:
        - BUILD_TYPE=Debug

install:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - (git clone https://github.com/google/googletest.git && cd googletest && git checkout release-1.8.1 && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make && sudo make install)
  - (git clone https://github.com/google/benchmark.git && cd benchmark && git checkout v1.4.1 && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_TESTING=OFF && make && sudo make install)

script:
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPLEIONE_DOC=OFF -DPLEIONE_PERF=ON -DCMAKE_EXE_LINKER_FLAGS=${LINK_FLAGS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS}
  - make VERBOSE=1
  - make test

after_script:
  - if [[ "${COVERAGE}" == 1 ]]; then
      cd ${TRAVIS_BUILD_DIR};
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info '/usr/*' --output-file coverage.info;
      lcov --list coverage.info;
      bash <(curl -s https://codecov.io/bash) -x gcov-8 || echo "Codecov did not collect coverage reports";
    fi
